# Patch xcodeproj to support objectVersion 71 (Xcode 26.x project format)
require 'xcodeproj'
unless Xcodeproj::Constants::COMPATIBILITY_VERSION_BY_OBJECT_VERSION.key?(71)
  patched = Xcodeproj::Constants::COMPATIBILITY_VERSION_BY_OBJECT_VERSION.dup.merge(71 => 'Xcode 16.1')
  Xcodeproj::Constants.send(:remove_const, :COMPATIBILITY_VERSION_BY_OBJECT_VERSION)
  Xcodeproj::Constants.const_set(:COMPATIBILITY_VERSION_BY_OBJECT_VERSION, patched.freeze)
end

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

min_ios_version = '17.0'
platform :ios, min_ios_version
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Insight' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Needed for DOCX unzip support used in `DocumentManager.swift`
  pod 'SSZipArchive'

  # Firebase Auth + Google Sign-In
  pod 'GoogleSignIn', '~> 8.0'
  pod 'FirebaseAuth'
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'RecaptchaInterop', :modular_headers => true

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Allow non-modular includes to avoid build errors from certain pods/headers
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_ios_version
      end

      # Some local pod states miss Public/glog header links; ensure Folly can
      # resolve <glog/logging.h> directly from pod sources.
      if target.name == 'RCT-Folly'
        target.build_configurations.each do |config|
          header_paths = config.build_settings['HEADER_SEARCH_PATHS'] || '$(inherited)'
          unless header_paths.include?('"${PODS_ROOT}/glog/src"')
            header_paths = "#{header_paths} \"${PODS_ROOT}/glog/src\""
          end
          config.build_settings['HEADER_SEARCH_PATHS'] = header_paths
        end
      end
    end
  end
end
